name: progresso
description: "Personal development tracking app with gamification features."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  supabase_flutter: ^2.9.1
  
  flutter_dotenv: ^6.0.0
  image_picker: ^1.2.0
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  intl: ">=0.19.0 <0.21.0"
  flutter_markdown: ^0.7.7
  flutter_quill: ^11.4.2
  google_fonts: ^6.3.0
  flutter_image_compress: ^2.3.0
  cached_network_image: ^3.4.1
  sentry_flutter: ^9.6.0
  url_launcher: ^6.3.2
  package_info_plus: ^8.0.2
  web: ^1.1.0
  fl_chart: ^1.0.0
  sqflite: ^2.3.0
  path: ^1.8.3
  uuid: ^4.5.1
  file_picker: ^10.3.2
  share_plus: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  riverpod_generator: ^2.3.9
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  sqflite_common_ffi: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/default_avatar.png
    - .env
  generate: true

# Using non-synthetic localization package per l10n.yaml