name: progresso
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  json_annotation: ^4.9.0
  supabase_flutter: ^1.10.25
  flutter_dotenv: ^5.1.0
  image_picker: ^0.8.9
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  intl: ">=0.19.0 <0.21.0"
  flutter_markdown: ^0.6.18
  flutter_quill: ^11.4.2
  google_fonts: ^6.3.0
  flutter_image_compress: ^2.4.0
  cached_network_image: ^3.4.1
  sentry_flutter: ^8.7.0
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/default_avatar.png
  generate: true

# Using non-synthetic localization package per l10n.yaml