name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flutter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
      - name: Pub get
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Build runner (if needed)
        run: flutter packages pub run build_runner build --delete-conflicting-outputs || true
      - name: Tests
        run: flutter test
      - name: Build Android APKs (split per ABI)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: |
          flutter build apk --release --split-per-abi \
            --dart-define=FLAVOR=staging \
            --dart-define=SUPABASE_URL=$SUPABASE_URL \
            --dart-define=SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY \
            --dart-define=SENTRY_DSN=$SENTRY_DSN
      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: android-apks
          path: build/app/outputs/flutter-apk/*.apk
name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    # No local .env in CI: use --dart-define wherever a build is executed
    
    - name: Clean project
      run: flutter clean
    
    - name: Generate code
      run: flutter packages pub run build_runner build --delete-conflicting-outputs
      continue-on-error: true
    
    - name: Analyze project source
      run: flutter analyze
      continue-on-error: true
    
    - name: Run simple unit tests
      run: flutter test test/unit/simple_test.dart --reporter=expanded
      continue-on-error: true
    
    - name: Run simple widget tests
      run: flutter test test/widget/simple_widget_test.dart --reporter=expanded
      continue-on-error: true
    
    - name: Run all unit tests
      run: flutter test test/unit/ --reporter=expanded
      continue-on-error: true
    
    - name: Run all widget tests
      run: flutter test test/widget/ --reporter=expanded
      continue-on-error: true
    
    - name: Run integration tests
      run: flutter test test/integration/ --reporter=expanded
      continue-on-error: true
    
    - name: Build for web
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      run: |
        flutter build web --no-tree-shake-icons --web-renderer html \
          --dart-define=FLAVOR=staging \
          --dart-define=SUPABASE_URL=$SUPABASE_URL \
          --dart-define=SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY \
          --dart-define=SENTRY_DSN=$SENTRY_DSN
      continue-on-error: true
    
    - name: Build for Windows
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      run: |
        flutter build windows --no-tree-shake-icons \
          --dart-define=FLAVOR=staging \
          --dart-define=SUPABASE_URL=$SUPABASE_URL \
          --dart-define=SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY \
          --dart-define=SENTRY_DSN=$SENTRY_DSN
      continue-on-error: true

  build-windows:
    runs-on: windows-latest
    needs: test
    timeout-minutes: 15
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    # No local .env in CI
    
    - name: Clean project
      run: flutter clean
    
    - name: Generate code
      run: flutter packages pub run build_runner build --delete-conflicting-outputs
      continue-on-error: true
    
    - name: Build Windows executable
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      run: |
        flutter build windows --release --no-tree-shake-icons \
          --dart-define=FLAVOR=staging \
          --dart-define=SUPABASE_URL=$SUPABASE_URL \
          --dart-define=SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY \
          --dart-define=SENTRY_DSN=$SENTRY_DSN
      continue-on-error: true
    
    - name: Upload Windows build
      uses: actions/upload-artifact@v4
      with:
        name: progresso-windows
        path: build/windows/x64/runner/Release/
      if: success() || failure()

  build-web:
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    # No local .env in CI
    
    - name: Clean project
      run: flutter clean
    
    - name: Generate code
      run: flutter packages pub run build_runner build --delete-conflicting-outputs
      continue-on-error: true
    
    - name: Build web
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      run: |
        flutter build web --release --no-tree-shake-icons --web-renderer html \
          --dart-define=FLAVOR=staging \
          --dart-define=SUPABASE_URL=$SUPABASE_URL \
          --dart-define=SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY \
          --dart-define=SENTRY_DSN=$SENTRY_DSN
      continue-on-error: true
    
    - name: Upload web build
      uses: actions/upload-artifact@v4
      with:
        name: progresso-web
        path: build/web/
      if: success() || failure() 