name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Create .env file
      run: |
        echo "SUPABASE_URL=https://xssuhovxkpgorjxvflwo.supabase.co" > .env
        echo "SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhzc3Vob3Z4a3Bnb3JqeHZmbHdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5ODY2NTEsImV4cCI6MjA2OTU2MjY1MX0.y1fXBKBAQkNL17AcBiBNMIOyVyBD8_fexQWeWqGz1UY" >> .env
    
    - name: Clean project
      run: flutter clean
    
    - name: Generate code
      run: flutter packages pub run build_runner build --delete-conflicting-outputs
      continue-on-error: true
    
    - name: Analyze project source
      run: flutter analyze --no-fatal-infos
      continue-on-error: true
    
    - name: Run simple unit tests
      run: flutter test test/unit/simple_test.dart --reporter=expanded
      continue-on-error: true
    
    - name: Run simple widget tests
      run: flutter test test/widget/simple_widget_test.dart --reporter=expanded
      continue-on-error: true
    
    - name: Run all unit tests
      run: flutter test test/unit/ --reporter=expanded
      continue-on-error: true
    
    - name: Run all widget tests
      run: flutter test test/widget/ --reporter=expanded
      continue-on-error: true
    
    - name: Run integration tests
      run: flutter test test/integration/ --reporter=expanded
      continue-on-error: true
    
    - name: Build for web
      run: flutter build web --no-tree-shake-icons --web-renderer html
      continue-on-error: true
    
    - name: Build for Windows
      run: flutter build windows --no-tree-shake-icons
      continue-on-error: true

  build-windows:
    runs-on: windows-latest
    needs: test
    timeout-minutes: 15
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Create .env file
      run: |
        echo "SUPABASE_URL=https://xssuhovxkpgorjxvflwo.supabase.co" > .env
        echo "SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhzc3Vob3Z4a3Bnb3JqeHZmbHdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5ODY2NTEsImV4cCI6MjA2OTU2MjY1MX0.y1fXBKBAQkNL17AcBiBNMIOyVyBD8_fexQWeWqGz1UY" >> .env
    
    - name: Clean project
      run: flutter clean
    
    - name: Generate code
      run: flutter packages pub run build_runner build --delete-conflicting-outputs
      continue-on-error: true
    
    - name: Build Windows executable
      run: flutter build windows --release --no-tree-shake-icons
      continue-on-error: true
    
    - name: Upload Windows build
      uses: actions/upload-artifact@v4
      with:
        name: progresso-windows
        path: build/windows/x64/runner/Release/
      if: success() || failure()

  build-web:
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Create .env file
      run: |
        echo "SUPABASE_URL=https://xssuhovxkpgorjxvflwo.supabase.co" > .env
        echo "SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhzc3Vob3Z4a3Bnb3JqeHZmbHdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5ODY2NTEsImV4cCI6MjA2OTU2MjY1MX0.y1fXBKBAQkNL17AcBiBNMIOyVyBD8_fexQWeWqGz1UY" >> .env
    
    - name: Clean project
      run: flutter clean
    
    - name: Generate code
      run: flutter packages pub run build_runner build --delete-conflicting-outputs
      continue-on-error: true
    
    - name: Build web
      run: flutter build web --release --no-tree-shake-icons --web-renderer html
      continue-on-error: true
    
    - name: Upload web build
      uses: actions/upload-artifact@v4
      with:
        name: progresso-web
        path: build/web/
      if: success() || failure() 