name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ios:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
      - name: Xcode version
        run: xcodebuild -version
      - name: Pub get
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Tests
        run: flutter test
      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign --dart-define=FLAVOR=staging
      - name: Upload iOS build
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/iphoneos
