name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ios:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
      - name: Xcode version
        run: xcodebuild -version
      - name: Pub get
        run: flutter pub get
      - name: Analyze (treat warnings as non-fatal)
        run: |
          set -o pipefail
          flutter analyze || true
      - name: Tests
        run: flutter test --reporter expanded
      - name: Build iOS (no codesign)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: |
          flutter build ios --release --no-codesign \
            --dart-define=FLAVOR=staging \
            --dart-define=SUPABASE_URL=$SUPABASE_URL \
            --dart-define=SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY \
            --dart-define=SENTRY_DSN=$SENTRY_DSN
      - name: Upload iOS build
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/iphoneos
